### ISSUE TITLE
JOSS Review (jspaezp)

### ISSUE THREAD

**Issue by jspaezp** [sdrogers/vimms#230]
Review checklist for @jspaezp for JOSS https://github.com/openjournals/joss-reviews/issues/3990

- [x] I confirm that I have read the JOSS conflict of interest (COI) policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

Code of Conduct

- [x]  I confirm that I read and will adhere to the JOSS code of conduct.

General checks

- [x] Repository: Is the source code for this software available at the repository url?
- [x] License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
- [x] Contribution and authorship: Has the submitting author (@joewandy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x]  Substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines

Functionality

- [x] Installation: Does installation proceed as outlined in the documentation?
    - The installation mentions `ViMMS requires Python 3+. Unfortunately it is not compatible with Python 2. You can install a stable version of ViMMS using pip or pipenv.`. I don't think this line is needed, since Py2 has reached EOL, therefore it is reasonable to assume that Python 3.6+ will be used.
- [x] Functionality: Have the functional claims of the software been confirmed?
- [x] Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

Documentation

- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
    - [x] there is mention of `git clone https://github.com/sdrogers/vimms.git`, please update to the new repository url (glasgowcompbio/vimms)
    - [x] https://github.com/glasgowcompbio/vimms/blob/25afd804479ddb58cd30ed93287428872b1a8adc/setup.py#L15 same here
- [x] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
    - [x] `RoiToChemicalCreator` is imported in the examples, which raises `ImportError: cannot import name 'RoiToChemicalCreator' from 'vimms.Roi' (~/.local/share/virtualenvs/vimms-j1m4gYsN/lib/python3.9/site-packages/vimms/Roi.py)` please update the examples or add annotations to the directories specifying which ones are meant to run from the current master branch (and ideally if they were meant to run in the past, what commit that was)
- [x] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
    - The long form documentation is exemplary good (examples/demos) but the API and code level documentation (readthedocs/docstrings) is not great, I believe that adding much better information on the parameters is required.
    - [x] Parameter docstrings
- [x] Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
    - [x] Please add a README to `https://github.com/glasgowcompbio/vimms/tree/master/tests/fixtures/` with instructions on how to generate those files. (and ideally remove those files so they are generated and cached during the testing process).
    - [ ] I believe a codecov report should be added to the CI pipeline
- [x] Community guidelines: Are there clear guidelines for third parties wishing to
    1) [x] Contribute to the software
        - **I would appreciate if the guideline included any specifics on what linter/checker/testing framework to use during the code contribution. (not critical)**
        -  [x] Is there any intention of making the code flake8 compliant? I noticed the CI checks for it but based on the number of "violations" I don't see the point of having it (https://github.com/glasgowcompbio/vimms/runs/4901527800?check_suite_focus=true)
    2) [x] Report issues or problems with the software 
    3) [x] Seek support

1. On the README there is the reference to: `Run Jupyter ($ jupyter lab) so you could run the example notebooks below.`, please add a link to the notebooks being referenced.

Software paper

- [x] Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] A statement of need: Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is - [] designed to solve and who the target audience is?
- [x] State of the field: Do the authors describe how this software compares to other commonly-used packages?
- [x] Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

Code Review:

1. https://github.com/glasgowcompbio/vimms/blob/387279719b7769658b267846aee3dfa8ee6dfa0c/vimms/Common.py#L278-L281
    1. Should a warning be thrown if the length of the path is "." instead of just silently ignoring the command?
    2.  I believe that check is redundant with the behavior of pathlib.Path.mkdir
2. https://github.com/glasgowcompbio/vimms/blob/387279719b7769658b267846aee3dfa8ee6dfa0c/vimms/Common.py#L305-L316
    1. I believe this function should throw an error when the file cannot be open instead of a warn and returning None
3.  https://github.com/glasgowcompbio/vimms/blob/387279719b7769658b267846aee3dfa8ee6dfa0c/vimms/Common.py#L319-L327
    1. Should an assertion be added to make sure the two iterables have the same length? As it is right now it will silently give a wrong answer when `len(intensities) > len(rts)` but break when `len(rts) > len(intensities)`
4. https://github.com/glasgowcompbio/vimms/blob/387279719b7769658b267846aee3dfa8ee6dfa0c/vimms/Common.py#L16
    1. I suggest you import tqdm as `from tqdm.auto import tqdm`, since it handles better progress bars in different plattaforms (automatically selects a notebook/terminal bar) 
5. I think the object nomenclature should be a little more clear when saving pickled objects. Since the `save_obj` function saves files as gzipped pickled objects, having the extension be `.p.gz` could be more appropriate than `.p`
6. Empty `vimms/demo/03. MultiSampleMethods/`
7. Is there any reason `vimms/notebook` is in that location? (inside the package itselt) 
8. https://github.com/glasgowcompbio/vimms/blob/94da3c7654429a6e2e36383666b002194d951cc5/vimms/Controller/base.py#L55 I believe this should be an instance of `from abc import ABC` and have the methods required for the functioning of the class be abstractmethods  `@abc.abstractmethod`. So errors are raised during instantiation and not during calling of the method.
    9.  https://github.com/glasgowcompbio/vimms/blob/69afe3af55e98138bdb0f95a09302b7117eb18ff/vimms/Agent.py#L12 same here
9. https://github.com/glasgowcompbio/vimms/blob/2162c09203fa8899015ff658bf57642259f857bb/vimms/Controller/vinny_test.py#L200 Raising not implemented errors should be written as `raise NotImplementedError`
10. `vimms/old_unused_experimental` please remove from the main repository (potentially generate a branch so they are not "lost") 
11. https://github.com/glasgowcompbio/vimms/blob/453e989f4e26c50c0e20a1e887c53e012bd040ad/vimms/Chemicals.py#L37 This definition should probably come from vimms.Common

**Comment by joewandy** [comment]
Dear Juan (@jspaezp),

Thank you for your review. Your extensive comments have led to a large improvement in the software quality of the ViMMS project, and behalf of the entire team, I'd like to say that we really appreciate the effort.

The following is an itemised list of the issues found, and our comments to address them:

--

> 1. Contribution and authorship: Has the submitting author (@joewandy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

Our reply: I believe I've made a major contribution to the software 🙂 as you can see from the commit history. Other authors listed in the paper have also contributed appropriately as seen from the [Contributors page](https://github.com/glasgowcompbio/vimms/graphs/contributors) on Github. 

--

> 2. Functionality: Have the functional claims of the software been confirmed?
> 3. Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Our reply: The functional claims of the software couldn't be verified because the example and demo notebooks were broken. We've since updated all notebooks to make sure they run.

--

> 4. Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

Our reply: the API documentation was indeed lacking. We've since improved the API documentation at https://vimms.readthedocs.io to be more comprehensive, including having better docstrings on the codes and parameters required. However since the project is still actively developed, some parts of the codes are not entirely documented yet, so this is an on-going work. Over time we will also update the codebase and documentation to include type information.

--

> 5. Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

Our reply: a [README](https://github.com/glasgowcompbio/vimms/tree/master/tests/fixtures) has been added to explain the test fixtures and how they were generated. We'd look those files can be generated and cached during the testing process.

Coverage report has also been added to the CI, as seen [here](https://github.com/glasgowcompbio/vimms/runs/5423264281?check_suite_focus=true).

--

> 6. Community guidelines: Are there clear guidelines for third parties wishing to ...

Our reply: We have now included a Contributing guideline [here](https://github.com/glasgowcompbio/vimms/blob/master/CONTRIBUTING.md), and made sure that it's now linked from the README. The Contributing guideline details the linter, testing and documentation framework used for anybody who wishes to contribute. 

It took a while, but we've also fixed [all the flake8 violations](https://github.com/glasgowcompbio/vimms/runs/5423264281?check_suite_focus=true), as well as agreeing among ourselves not to introduce new ones in the future.

--

> 7. Code review:

Our reply:
- 1, 2, 3, 6, 9, 11 are fixed
- 4: thank you for the suggestion to import from `tqdm.auto`. The progress bar looks a lot nicer now.
- 7: `vimms/notebook` shouldn't be there and it has been moved out from the package itself
- 8, 9: we properly implement these classes as abstract classes now.
- 10: those experimental files have been moved to their own `old_unused_experimental ` branch.

--

I hope these changes are satisfactory to address the issues above. If there's any other problem, please let me know.

Thank you,

Joe Wandy (on behalf of the ViMMS team)
