### ISSUE TITLE
Top-N controller is broken when running on IAPI

### ISSUE THREAD

**Issue by joewandy** [sdrogers/vimms#3]
Changes:

1. Do not schedule new custom scan until a duty cycle has been completed (1 ms2 + N ms2s).

- Schedule an ms1
- Schedule N ms2 + 1 ms1
- Ignore other method MS1 scans that come from the mass spec

2. Dynamic exclusion is not working, is it because IAPI returns scan start time in minutes, while we're expecting seconds?

3. It's still not clear if we should use this `SingleProcessingDelay` parameter or just set it to 0 (now it's set to 0.5s).

> SingleProcessingDelay: The instrument will not execute any further custom scan if this property is positive until the delay has expired or a new custom scan has been defined. The unit of this property is seconds and possible values are between 0 and 600 inclusively. The default value is 0.

**Comment by joewandy** [comment]
Hi all,

Thanks for the zoom — think we’re getting there.

Just to summarise what the next steps are:

1. Remove weird 500ms parameter….
2. Modify controller — I propose having it schedule a block consisting of N MS2 and then an MS1 and then just only scheduling when it receives an MS1 (see below).
3. Re-test :-)
No problems with further developing the simulator — it’ll be necessary. Just be good to really maximise any opportunities on the machine. ROI top-N is a really easy method / paper to get out.

Controllers:
How about this for a flexible approach:
 - Scans are scheduled in blocks by some method (call it schedule). When schedule is called, it is passed the info it will need (e.g. the most recent scan) and it, after scheduling, returns the scan number of the last one in its block.
 - The controller records this number, and calls schedule again once this scan has arrived (passing it the scan). Each schedule method could also return what should be the next schedule method to be run…

So, for example, there are two ways of doing top-N…

Method 1:
a. Have a schedule method (called single_ms1) that just places an MS1 and returns its ID another schedule method that will do the bulk of the top-N (call it topN)
b. when the scan number returned by single_ms1 is received, topN is called, passing it the scan
c. topN schedules N MS2 and an MS1. Returns the ID of the MS1 and says that the next method to be called is topN again
d. Once the scan with that ID is received, topN is called again etc etc

Method 2:
a. As above
B. As above
c. topN schedules N MS2 and returns the ID of the last one. Next method to be called is single_ms1
d. When the relevant scan is received, it calls single_ms1
e. When the scan places by single_ms1 is received, it calls topN

I think we could build pretty much anything into this system…only issue will be if there are still large delays and we want to remove them by MS1 scans happening by default…but let’s try it and see if that is a problem.

Simon

**Comment by sdrogers** [comment]
Seems we're still not quite there... I have a few queries about the code...
In `IAPIEnvironment`:
I don't understand this...
```
            self.scan_channel.append(scan)
            scan = self.scan_channel.pop(0)
```
Does this mean that there could be multiple scans in the `scan_channel`? Otherwise, not sure why we put it in the channel and then pop it straight back out?

This then fires the `handle_scan` method of the `Controller` class.
Within this method we call `_plot_scan()` -- could this cause unnecessary delay?

Then I have some questions about the topN thing (looking at the topN controller on IAPI branch)...
1. Where are the MS1 scans scheduled? I cannot find the relevant bit of the topN controller. Can someone point me to the relevant code please!?
2. We don't seem to check anything about the ms1 scans...I think some method scans get into the system at the beginning (there are 3 in the mzml at the start, and then no more) and I suspect we process them (they generate ms2).
3. My understanding of the top-N process is that we only process *our* MS1 scans. At the very beginning, we need to schedule _one_. Then if we simply schedule one at the end of each MS2 block (i.e. the end of `_process_scans`)
4. How *simultaneous* are things. I.e. do all MS2 get sent to the machine once we've scheduled them all, or do we send each one as we make it?

*Note*: Please remove the 0.5second thing...it's still there (visible in the logs)

**Comment by sdrogers** [comment]
Update: I found the ms1 scan generation -- it's in the Mass Spec class. And it still sends an ms1 scan then there is nothing in the queue??

I don't think this is every going to work -- it's like we're semi-emulating the method scan on the machine. So, we have three separate things now that can generate scans...the machine...(method), the IAPAMS class ("method") and the controller....I suggest in the IAPA MS class we shouldn't be generating "method" scans...

**Comment by sdrogers** [comment]
The issue is in the `_get_params()` method of the `IndependentMassSpectrometer` class

This is not overridden in the `IAPIMassSpectrometry` class but is called in `_send_custom_scan()`

If there is nothing in the queue, `_get_params()` returns an ms1 scan.

Fix:
1. override `_get_params()` in the IAPIMassSpectrometer` class so that it returns `None` if there is nothing in the queue.
2. Add two things to the controller(s)...All controllers that are top-N based...
  a) scheduling of initial MS1 scan
  b) schedule an MS1 scan at the end of each MS2 block

The same issues are in all of the controllers, because the `IAPIMassSpectrometer` class is firing these MS1 for everything

And please check the following:
1. Remove the single scan processing (set to 0)
2. Check *why* we are scheduling MS2 from method scans (right at the start). Can be fixed by checking the spectrum number. If it is less than the first number we use, ignore it (in the controller)
3. Also, why do the method scans at the start end up in the mzml?
4. What is currently happening when we have multiple MS1 at our end. Which one are we processing?
5. Synchronisation: can we fire an event whenever we add any custom scan to the queue? At the moment, I *think* we process the MS1, create the MS2 scans, and then send them *all* to the next stage. It would be better to be able to send them as they are made.

**Comment by joewandy** [comment]
So .. Vinny and I pushed a number of commits in the `iapi` branch to implement the 3 fixes above. Hopefully we'd have the chance to test them soon.

And for the questions above.

*1. Remove the single scan processing (set to 0)* 

Done.

*2. Check why we are scheduling MS2 from method scans (right at the start). Can be fixed by checking the spectrum number. If it is less than the first number we use, ignore it (in the controller)*

Code has been changed to not schedule MS2 from method scans.

*3. Also, why do the method scans at the start end up in the mzml?*

Why not? Even if we don't process them, we should still record them.

*4. What is currently happening when we have multiple MS1 at our end. Which one are we processing?*

The MS1 scan that will be processed is the last MS1 scan in a block of scan that we'd sent out.

*5. Synchronisation: can we fire an event whenever we add any custom scan to the queue? At the moment, I think we process the MS1, create the MS2 scans, and then send them all to the next stage. It would be better to be able to send them as they are made.*

True. So at the moment, the workflow goes like this: we process an MS1 scan, create all the MS2 custom scan commands from it, push them all into the queue of the mass spec, wait for FusionBridge to issue the `CanAcceptNextCustomScan` event. Each time this event is triggered, we pop one custom scan command from the queue and forward it to IAPI. 

This is probably not a problem as long as the time it takes to create the whole batch of MS2 scan commands is quick, but would be better if we send each scan command as it's created. Will change the code to do this.
